AllCops:
    Exclude:
        - '**/*.gemspec'
        - '**/*.spec'

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 20

Style/AccessorMethodName:
  Enabled: False

Metrics/PerceivedComplexity:
  Max: 20

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 130

Metrics/BlockLength:
  Enabled: False

# Puppet style
Style/SignalException:
  Enabled: False

Layout/IndentHeredoc:
  Enabled: False

Style/SymbolArray:
  Enabled: False

Style/PercentLiteralDelimiters:
  Enabled: False
